# Generated by Django 3.2.12 on 2022-04-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='runtime',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('runtime', 'provider')},
        ),
    ]
