# Generated by Django 3.2.12 on 2022-04-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0002_auto_20220414_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer',
            new_name='properties',
        ),
    ]
