# Generated by Django 3.2.12 on 2022-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0003_rename_offer_offer_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='monthly_price_glm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
