# Generated by Django 4.1.7 on 2023-12-21 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0004_offer_monthly_price_glm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('online', models.BooleanField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_events', to='api2.node')),
            ],
        ),
        migrations.CreateModel(
            name='NodeUptime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_uptime', models.DurationField(default=datetime.timedelta)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uptime', to='api2.node')),
            ],
        ),
    ]
