# Generated by Django 4.1.7 on 2024-01-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0005_healtchecktask'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.FloatField(null=True)),
            ],
        ),
    ]
