# Generated by Django 4.1.7 on 2024-01-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0006_glm'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='monthly_price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
