# Generated by Django 4.1.7 on 2024-01-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0006_healtchecktask_remove_uptimeevent_node_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healtchecktask',
            name='status',
            field=models.TextField(),
        ),
    ]
