# Generated by Django 4.1.7 on 2024-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0007_offer_monthly_price_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('vcpu', models.IntegerField(null=True)),
                ('memory', models.FloatField(null=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
