# Generated by Django 4.1.7 on 2024-01-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0008_ec2instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_overpriced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='overpriced_compared_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api2.ec2instance'),
        ),
    ]
