# Generated by Django 4.1.7 on 2024-01-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0010_offer_suggest_env_per_hour_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='times_more_expensive',
            field=models.FloatField(null=True),
        ),
    ]
