# Generated by Django 4.1.7 on 2024-02-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0012_offer_cheaper_than_offer_times_cheaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.node')),
            ],
        ),
    ]
