# Generated by Django 4.1.7 on 2024-02-21 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0013_nodestatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='uptime_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
