# Generated by Django 4.1.7 on 2024-02-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0014_node_uptime_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hourly_price_glm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='hourly_price_usd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
