# Generated by Django 4.1.7 on 2024-02-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0015_offer_hourly_price_glm_offer_hourly_price_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderWithTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_per_hour', models.FloatField(blank=True, null=True)),
                ('env_per_hour', models.FloatField(blank=True, null=True)),
                ('start_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to='api2.node')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api2.offer')),
            ],
        ),
    ]
