# Generated by Django 4.1.7 on 2024-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0016_providerwithtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerwithtask',
            name='network',
            field=models.CharField(default='mainnet', max_length=42),
        ),
    ]
