# Generated by Django 4.1.7 on 2024-02-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0017_providerwithtask_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_cpu_price', models.FloatField(default=0)),
                ('median_cpu_price', models.FloatField(default=0)),
                ('average_env_price', models.FloatField(default=0)),
                ('median_env_price', models.FloatField(default=0)),
                ('average_start_price', models.FloatField(default=0)),
                ('median_start_price', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
