# Generated by Django 4.1.7 on 2024-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0018_pricingsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsnapshot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
