# Generated by Django 4.1.7 on 2024-02-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0020_pricingsnapshot_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='network',
            field=models.CharField(default='mainnet', max_length=42),
        ),
    ]
