# Generated by Django 4.1.7 on 2024-02-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0021_node_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsnapshot',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
