# Generated by Django 4.1.7 on 2024-03-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0022_alter_pricingsnapshot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=42, unique=True)),
            ],
        ),
    ]
