# Generated by Django 4.1.7 on 2024-03-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0023_relaynodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolemTransactions',
            fields=[
                ('scanner_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('txhash', models.CharField(max_length=66)),
                ('transaction_type', models.CharField(blank=True, max_length=42, null=True)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('receiver', models.CharField(max_length=42)),
                ('sender', models.CharField(max_length=42)),
                ('tx_from_golem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionScraperIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexed_before', models.BooleanField(default=False)),
                ('latest_timestamp_indexed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
