# Generated by Django 4.1.7 on 2024-03-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0024_golemtransactions_transactionscraperindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golemtransactions',
            name='receiver',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='golemtransactions',
            name='scanner_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='golemtransactions',
            name='sender',
            field=models.CharField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='golemtransactions',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='golemtransactions',
            name='transaction_type',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='golemtransactions',
            name='tx_from_golem',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='golemtransactions',
            name='txhash',
            field=models.CharField(db_index=True, max_length=66),
        ),
        migrations.AddIndex(
            model_name='golemtransactions',
            index=models.Index(fields=['txhash'], name='api2_golemt_txhash_205c12_idx'),
        ),
        migrations.AddIndex(
            model_name='golemtransactions',
            index=models.Index(fields=['transaction_type'], name='api2_golemt_transac_b601e3_idx'),
        ),
        migrations.AddIndex(
            model_name='golemtransactions',
            index=models.Index(fields=['timestamp'], name='api2_golemt_timesta_f4c9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='golemtransactions',
            index=models.Index(fields=['receiver', 'sender'], name='api2_golemt_receive_d6425b_idx'),
        ),
    ]
