# Generated by Django 4.1.7 on 2024-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0025_alter_golemtransactions_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodestatushistory',
            name='is_online',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='nodestatushistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='nodestatushistory',
            index=models.Index(fields=['provider', 'timestamp'], name='api2_nodest_provide_64b3a2_idx'),
        ),
    ]
