# Generated by Django 4.1.7 on 2024-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0026_alter_nodestatushistory_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='earnings_total',
        ),
        migrations.AlterField(
            model_name='node',
            name='computing_now',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='network',
            field=models.CharField(db_index=True, default='mainnet', max_length=42),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(db_index=True, max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='uptime_created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='version',
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='node',
            name='wallet',
            field=models.CharField(blank=True, db_index=True, max_length=42, null=True),
        ),
    ]
