# Generated by Django 4.1.7 on 2024-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0029_node_api2_node_online_822fe4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaynodes',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='relaynodes',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
