# Generated by Django 4.1.7 on 2024-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0031_update_nodestatushistory'),
    ]

    operations = [

        migrations.AlterField(
            model_name='nodestatushistory',
            name='is_online',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='nodestatushistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
