# Generated by Django 4.1.7 on 2024-09-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0034_nodestatushistory_api2_nodest_node_id_220bdf_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='nodestatushistory',
            name='api2_nodest_provide_64b3a2_idx',
        ),
    ]
