# Generated by Django 4.1.7 on 2024-10-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0037_alter_node_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(db_index=True, default='provider', max_length=42),
        ),
    ]
