# Generated by Django 4.1.7 on 2024-12-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0038_node_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nodestatushistory',
            index=models.Index(fields=['node_id', 'is_online', 'timestamp'], name='api2_nodest_node_id_ff6427_idx'),
        ),
        migrations.AddIndex(
            model_name='nodestatushistory',
            index=models.Index(fields=['timestamp', 'is_online'], name='api2_nodest_timesta_f6216b_idx'),
        ),
    ]
