# Generated by Django 4.1.7 on 2025-02-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0039_nodestatushistory_api2_nodest_node_id_ff6427_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionscraperindex',
            name='currently_indexing',
            field=models.BooleanField(default=False),
        ),
    ]
