# Generated by Django 3.1.7 on 2021-03-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20210329_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
