# Generated by Django 3.2 on 2021-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20210329_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
