# Generated by Django 3.2 on 2021-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_alter_node_node_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='wallet',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
