# Generated by Django 3.2 on 2021-04-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_node_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='earnings_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
