# Generated by Django 3.2 on 2021-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_node_earnings_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='earnings_total',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
