# Generated by Django 3.2 on 2021-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_alter_node_earnings_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='earnings_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
