# Generated by Django 3.2 on 2021-04-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_networkstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStatsMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.IntegerField()),
                ('cores', models.IntegerField()),
                ('memory', models.FloatField()),
                ('disk', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
