# Generated by Django 3.2.2 on 2021-05-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0011_alter_networkstatsmax_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
