# Generated by Django 3.2.2 on 2021-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0012_node_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
