# Generated by Django 3.2.2 on 2021-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0013_alter_node_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvidersComputing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
    ]
