# Generated by Django 3.2.2 on 2021-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0014_providerscomputing'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAveragePricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('cpuh', models.FloatField()),
                ('perh', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMedianPricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField()),
                ('cpuh', models.FloatField()),
                ('perh', models.FloatField()),
            ],
        ),
    ]
