# Generated by Django 3.2.4 on 2021-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0017_node_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='version',
            field=models.CharField(default='0.0.0', max_length=5),
            preserve_default=False,
        ),
    ]
