# Generated by Django 3.2.4 on 2021-06-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0018_node_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earnings', models.FloatField()),
            ],
        ),
    ]
