# Generated by Django 3.2.4 on 2021-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0019_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=42, unique=True)),
                ('tasks_requested', models.FloatField()),
            ],
        ),
    ]
