# Generated by Django 3.2.4 on 2021-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0020_requestors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestors',
            name='tasks_requested',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
