# Generated by Django 3.2.8 on 2021-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0023_node_benchmark_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='benchmarked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
