# Generated by Django 3.2.9 on 2021-11-16 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0025_auto_20211116_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchmarks',
            name='benchmark_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='benchmarks',
            name='benchmarked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
