# Generated by Django 3.2.10 on 2022-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0027_rename_benchmarks_benchmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='computing_now',
            field=models.BooleanField(default=False),
        ),
    ]
