# Generated by Django 3.2.12 on 2022-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0028_node_computing_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='version',
            field=models.CharField(max_length=7),
        ),
    ]
