# Generated by Django 3.2.13 on 2022-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0029_alter_node_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='total_earnings',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
