# Generated by Django 3.2.15 on 2022-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0031_benchmark_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='hybrid',
            field=models.BooleanField(default=False),
        ),
    ]
