# Generated by Django 4.1.7 on 2024-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0032_node_hybrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkstats',
            name='cuda_cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkstats',
            name='gpu_memory',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='networkstats',
            name='gpu_models',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='networkstats',
            name='gpus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkstats',
            name='runtime',
            field=models.CharField(default='vm', max_length=64),
        ),
        migrations.AddField(
            model_name='networkstatsmax',
            name='cuda_cores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkstatsmax',
            name='gpu_memory',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='networkstatsmax',
            name='gpus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networkstatsmax',
            name='runtime',
            field=models.CharField(default='vm', max_length=64),
        ),
    ]
