# Generated by Django 4.1.7 on 2025-02-20 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0034_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestors',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
